export const NUMBER = 'NUMBER'
export const DELETE = 'DELETE'
export const SUM = 'SUM'
export const SUBTRACT = 'SUBTRACT'
export const MULTIPLY = 'MULTIPLY'
export const DIVIDE = 'DIVIDE'
export const RESET = 'RESET'
export const RESULT = 'RESULT'